name: MovecraftMultiworldExtensions
version: ${project.version}
main: net.trollyloki.movecraftmultiworldextensions.MovecraftMultiworldExtensions
api-version: '1.20.6'

description: Extensions for Movecraft multiworld including circumnavigation and automatic world switching
author: TrollyLoki

depend:
  - Movecraft
softdepend:
  - WorldGuard
  - Multiverse-Portals